### ISSUE TITLE
Can't play AAC  .m4a files

### ISSUE THREAD

**Issue by robbsz** [alexmurray/amberol-snap#11] opened 2024-07-13 00:08 UTC
Using the snap version of Amberol, when playing an AAC file, the song loads with the cover art but doesn't play. No waveform appears. When playing through the Amberol deb package installed through the Ubuntu repository, it plays fine. I don't have much experience with Snaps, I assume the container doesn't have the codec needed?

**Comment by alexmurray** [comment] 2024-07-23 02:44
Thanks for reporting this issue - I can reproduce it and see the following output when trying to open an aac file which I think confirms your suspicion - will see if I can determine what other packages we need to fix it:

```
WARN  amberol::audio::waveform_generator > Pipeline error: Error(Message { ptr: 0x7173b4002c10, type: "error", seqnum: 144, src: Some("uridecodebin"), structure: Some(GstMessageError { gerror: (GError) ((GError*) 0x7173b4002f80), debug: (gchararray) "../gst/playback/gsturidecodebin.c(1027): no_more_pads_full (): /GstPipeline:pipeline0/GstURIDecodeBin:uridecodebin:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4701): gst_decode_bin_expose (): /GstPipeline:pipeline0/GstURIDecodeBin:uridecodebin/GstDecodeBin:decodebin1:\nno suitable plugins found:\nMissing decoder: MPEG-4 AAC (audio/mpeg, framed=(boolean)true, mpegversion=(int)4, level=(string)2, base-profile=(string)lc, profile=(string)lc, rate=(int)48000, channels=(int)2, stream-format=(string)adts)\n" }) })
 WARN  amberol::audio::gst_backend        > GStreamer warning: Warning from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin1: There is no codec present that can handle the stream's type.
No decoder available for type 'audio/mpeg, framed=(boolean)true, mpegversion=(int)4, level=(string)2, base-profile=(string)lc, profile=(string)lc, rate=(int)48000, channels=(int)2, stream-format=(string)adts'.
../gst/playback/gsturidecodebin.c(960): unknown_type_cb (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin1
```

**Comment by alexmurray** [comment] 2024-07-24 01:44
The above commit should fix this - unfortunately it also significantly increases the size of the snap since the required plugin and the various libraries it depends on are not provided by the gnome sdk content snap. This should be available in the edge channel soon.

**Comment by alexmurray** [comment] 2024-07-24 02:30
I have just promoted this new version to the stable channel, closing this issue.

**Closed as completed by alexmurray** 2024-07-24 02:30 UTC

**Comment by robbsz** [comment] 2024-07-24 03:34
@alexmurray Thanks for taking the time to look into this issue and resolving it as well!
